[tls13_mps] Fixed compilation errors due to unreachable code
This commit prevents early return when TLS1_3 enabled,
TLS1_2 disabled and SOME_MODES_USE_MAC enabled.

Without the commit, the compilation fails due to unreachable code, e.g.

```
/Users/oshapira/git/mbedtls/library/ssl_msg.c:1723:13: error: code will never be executed [-Werror,-Wunreachable-code]
        if( mbedtls_ssl_safer_memcmp( mac_peer, mac_expect,
            ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/oshapira/git/mbedtls/library/ssl_msg.c:1625:9: error: code will never be executed [-Werror,-Wunreachable-code]
        rec->data_len -= padlen;
        ^~~
2 errors generated.

```

Signed-off-by: Omer Shapira <omer.shapira@gmail.com>