[tls13_mps] Fixing compilation error due to fallthrough
Recent clang fails to accept unannotated fallthrough in a switch case,
leading to a compilation error:

/Users/oshapira/git/mbedtls/library/mps/mps.c:2173:13: note: insert 'break;' to avoid fall-through
            default:

Signed-off-by: Omer Shapira <omer.shapira@gmail.com>